# Listener configuration
listener 1884
bind_address 0.0.0.0

# Allow anonymous clients to connect
allow_anonymous true

# Persistence settings
persistence true
persistence_location /mosquitto/data/

# Log settings
log_dest stdout
log_dest topic
log_type error
log_type warning
log_type information

# Include additional config files (if needed)
# include_dir /etc/mosquitto/conf.d
